modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="blueskiescustomization"
version="${file.jarVersion}"
displayName="BlueSkiesCustomization"
authors="Team Potato"
description='''

'''